- Cargo.toml
- src/elf.rs
- src/jit.rs
- src/lib.rs
- tests/ubpf_jit_x86_64.rs
- Set/get instruction count uses usize which should really only be used for pointers.  Switch to u64 instead
- Call verifier in all cases
- Remove div/0 when jitting code since it causes even valid mod operations to fail.  More investigation needed.  Following up with the original author (https://github.com/qmonnet/rbpf/issues/45)
> Fix types, call verifier, and remove div/0 on valid mod operation

- src/ebpf.rs
- src/lib.rs
- tests/misc.rs
The list of regions that helper verifier functions check to ensure valid parameters did not include the stack.
- Updated to include the stack
- Simplified the verifier to take u64 ptrs instead of references to the actual region
- Added test to verify that the stack is included in the verify regions
> Allow helper function parameters to be on the stack

- src/assembler.rs
- src/disassembler.rs
- src/ebpf.rs
- src/jit.rs
- src/lib.rs
- src/verifier.rs
- tests/assembler.rs
Add support for BPF instruction `callx <reg>` which is a function call to pc + reg<src>.  The instruction uses opcode 0x8d
> Support BPF register relative call instruction: `call <reg>`

- src/elf.rs
- src/lib.rs
- Add support for .data.rel.ro relocations and memory
- Add support for inter-section relocations (between any section and any section)
- Rework relocation handling to perform in-place rather then copy out, edit, and copy back in
> Add relro support and in-place relocation modifications

- src/assembler.rs
- src/disassembler.rs
- src/lib.rs
- tests/assembler.rs
Call register (callx) uses the instructions imm field to specify the register containing the address to
> Call register uses imm

- examples/load_elf.rs
- examples/uptime.rs
- src/ebpf.rs
- src/helpers.rs
- src/lib.rs
- tests/misc.rs
- tests/ubpf_verifier.rs
- tests/ubpf_vm.rs
Add support for helper functions to carry along a caller provided context structure.  Used initially to support dynamic memory allocaations via helper functions.
> Add support for helper contexts

- src/ebpf.rs
- src/elf.rs
- src/lib.rs
- tests/misc.rs
- tests/ubpf_vm.rs
When analyzing an error message or dump the most common way is to look at the elf dump to find out what the instruction is.  When dumping ELFs with `llvm-obj-dump` the instructions are reported starting at #29 so align the rbpf reporting so that the user does not have to do a translation for each instruction they attempt to look up.  Especially painful when analyzing a full trace.
> Report instruction # same as obj dump

- src/lib.rs
- tests/misc.rs
Original VM implementation casts the pc calculation to i16 for jump instructions.  This meant that a jump to a pc larger then max i16 would result in a crash of the vm.
Cast up to `isize` before doing calculation.  `isize` is much larger than the maximum allowed program size.
This fixes issue: https://github.com/solana-labs/solana/issues/5520#event-2556627391
> Fix Jumps to pc greater than i16

- src/lib.rs
The `callx` instruction specifies a register containing the virtual address of the instruction to jump to.  Subtract the virtual address of the first instruction in the `.text` segment to get the proper program counter to jump to.
> Fix callx base address

- src/elf.rs
- src/lib.rs
- Report max call depth
- Clean up messaging and enable debug print of instructions executed and max call depth reached.
> Report max frame depth

- src/ebpf.rs
- src/lib.rs
bincode deserialize requires a call depth greater than 10.  Bump to 20, that is at least sufficient to deserialize the Solana sysval account's data.
> Bump max frame_depth

- src/elf.rs
Multi-threaded linking of BPF is causing bad relocations to be generated in ELF files
https://github.com/solana-labs/solana/issues/3108
Forcing single-threaded linking resolves the issue.  In conjunction with a change to single-threaded linking of BPF projects, the VM should fail to load if any bad relocations are encountered.
> Fail ELF load if bad relocation encountered

- src/lib.rs
The `trace!` call commented out in this PR is an instruction-level debug message that shows details of the registers and what instruction is being executed, and is very useful to debug BPF programs.
Unfortunately, the logging crates used enable the formatting of this message even when the `trace` level is not enabled for this module.  In particular, if `trace` is enabled for any module (even one that does not exist) then this `trace!` message is formatted (but not printed).
The overhead formatting this message incurs a very large overhead and leads to transactions failing because they are taking too long.
> Remove trace! call that incurs overhead even when not enabled for this module

- src/lib.rs
- tests/ubpf_vm.rs
The mov32 instructions should clear the upper 32 bits and move imm into the lower 32 bits.  Rbpf uses an i32 for imm which was being sign-extended and placed into the 64bit register.  This resulted in the sign-extension extending into the upper 32 bits.
> Clear upper 32bits when using mov32 instruction

- examples/uptime.rs
- src/ebpf.rs
- src/helpers.rs
- src/jit.rs
- src/lib.rs
- tests/misc.rs
- tests/ubpf_vm.rs
Use trait objects to convey helper function context.  Allows for much richer context to be passed to helper functions
> Use trait objects to convey helper function context

- examples/uptime.rs
- src/ebpf.rs
- src/helpers.rs
- src/jit.rs
- src/lib.rs
- tests/misc.rs
- tests/ubpf_vm.rs
Only use trait objects when conveying context, otherwise, it's inefficient
> Only use trait objects for helpers with context

- Cargo.lock
- Cargo.toml
- examples/uptime.rs
- src/ebpf.rs
- src/elf.rs
- src/helpers.rs
- src/jit.rs
- src/lib.rs
- src/memory_region.rs
- src/user_error.rs
- src/verifier.rs
- tests/misc.rs
- tests/ubpf_verifier.rs
- tests/ubpf_vm.rs
* Rework error handling to use `thiserror` rather then io:error.
* Gets away from all errors being strings
* This will improve performance by reducing the number of &str to String allocations
* Use generics to allow callers to return their own error definitions from functions they register with the VM.  This provides more flexibility for callers to return what they want and not have to do conversions from strings.  Also allows callers to return their native error codes from Helpers
> Rework error handling to return user defined errors

- src/lib.rs
- src/memory_region.rs
- tests/misc.rs
In the execution loop the program counter served to both point to the next instruction and referred to the current as `pc -1` which was confusing.  Rework how the program counter variable is used so that `next_pc` is the next program counter and `pc` is the current.
> Cleanup program counter representation

- src/vm.rs
- tests/misc.rs
- vm_addr was actually the host address based on mem.as_ptr().
- len was always 8 bytes, even for smaller accesses, causing the regions bounds check to fail.
Note: Also, adds a separate test of vm LD_ABS to demonstrate the bug. The test can be recombined with the jit test later again.
> Fixes address translation of LD_ABS and LD_IND in vm execute_program_inner

- src/memory_region.rs
- src/vm.rs
This gives logarithmic time complexity for address translation.
It also fixes the following bug:
If a region is mapped at the upper end of the vm address space (e.g. a stack), then one could circumvent the upper bounds check by accessing the max address.
self.addr_vm + self.len = 0xFFFFFFFFFFFFFFFF
vm_addr = 0xFFFFFFFFFFFFFFFF
vm_addr.saturating_add(len as u64) is still 0xFFFFFFFFFFFFFFFF
0xFFFFFFFFFFFFFFFF <= self.addr_vm + self.len
Thus, no error is detected and one can reach into the unmapped host address space behind the end of the mapping.
> Use binary search in address translation

- .travis.yml
- examples/uptime.rs
- src/elf.rs
- src/verifier.rs
- src/vm.rs
- tests/assembler.rs
- tests/common.rs
- tests/misc.rs
- tests/ubpf_verifier.rs
- tests/ubpf_vm.rs
These changes enable the caller to pre-build an executable that can later be passed to the VM to execute.  Doing so allows use cases where the caller might want to create and cache an executable rather than create it every time they want to execute.
> Execute on pre-loaded binaries

- src/jit.rs
- src/vm.rs
- tests/misc.rs
Changes calling convention to correctly receive mem parameter.
From Microsoft x64 to System V, AMD64, Solaris, Linux, FreeBSD, macOS.
Also removes the check in vm.rs jit_compile() which prevents the JIT tests from running.
> Fix JIT linear address translation

- src/jit.rs
- src/vm.rs
- tests/misc.rs
> JIT syscall

- src/elf.rs
- src/error.rs
- src/jit.rs
- src/user_error.rs
- src/verifier.rs
- tests/misc.rs
Implements EbpfError::DivideByZero in JIT and adds a test for it.
> EbpfError::DivideByZero in JIT

- README.md
- examples/uptime.rs
- src/call_frames.rs
- src/error.rs
- src/helpers.rs
- src/jit.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_vm.rs
Combines all regions into one `memory_mapping` which can be transported through the interpreter and JIT likewise,
so both can use `translate_addr` in memory_region.rs
> Unify VM and JIT address translation

- src/jit.rs
- src/memory_region.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_unified.rs
Adds support for dynamic BPF calls (`CALL_REG`) and target address bounds check to JIT
using a lookup table to translate the target address.
Also, converts the tests for it and fixes the reporting of `EbpfError::CallOutsideTextSegment` in VM interpreter.
> Dynamic BPF Calls in JIT

- src/call_frames.rs
- src/error.rs
- src/jit.rs
- tests/misc.rs
- tests/ubpf_unified.rs
* Protect against manipulation of the BPF stack pointer. Stores it on the JITs stack frame as a local variable, and resets the BPF stack pointer on every `call` and `exit` (return).
* Trigger exception on stack overflow.
> JIT BPF Stack Guard

- src/jit.rs
Currently we are using a RISCy pattern: Load, modify and store values.
This PR changes the ALU instruction emitter to support register indirect memory operands.
This way we can make use of the CISCy nature of the x86 ISA.
> Refactor JIT Instruction Emitter

- README.md
- examples/uptime.rs
- src/error.rs
- src/jit.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_unified.rs
The instruction meter is only validated and updated on branching instructions.
> JIT Instruction Meter

- examples/uptime.rs
- src/error.rs
- src/jit.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Adds support for syscalls consuming the instruction meter in JIT while the program is running.
> JIT Consuming Instruction Meter in Syscalls

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- examples/uptime.rs
- src/elf.rs
- src/error.rs
- src/jit.rs
- src/syscalls.rs
- src/vm.rs
- test_utils/Cargo.lock
- test_utils/src/lib.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Changes:
- JIT compile and Config moved from VM to Executable
- Syscall registration split:
- Function pointers are registered in SyscallRegistry (via hash or name)
- SyscallRegistry is passed to Executable
- Context objects are bound in VM (via dyn trait)
- All syscalls have context objects now (no more function only)
- The context object instances of syscalls are stored in a table and accessed dynamically at runtime
- Syscalls return type became an &mut parameter (because of conflict with the &mut self parameter)
- PC loc jump table inlined into compiled function
- JIT syscalls became more efficient as the register moves to shuffle the arguments are not necessary anymore
- Security: JIT function permissions corrected (removed write permission on executable pages)
> Refactoring for JIT compilation cache

- benches/elf_loader.rs
- benches/memory_mapping.rs
- src/call_frames.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
Reduces the run time complexity of stack regions in address translation from O(log n) to O(1) using bitshifts as division. This is possible as all stack frames are aligned and the gaps in between them have the same size as the frames themselves. With this, we can increase the stack size arbitrarily (except for memory limits of course), as the time needed for their address translation is now constant.
All other address translations are (almost) unaffected as the benchmarks don't indicate any regression outside of the variance / fluctuation. However, stack frames caused the most regions to be mapped, so this should help in general.
> Gapped Address Translation

- benches/elf_loader.rs
- benches/memory_mapping.rs
- src/call_frames.rs
- src/jit.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
Measured the following sizes of generated machine code for various expensive operations:
* Address translation: 104 bytes
* Instruction profiling and limiting: 20 bytes
* Syscall: 238 bytes
* BPF-to-BPF static call: 98 bytes
* BPF-to-BPF dynamic call: 185 bytes
* Exit / return: 68 bytes
Based on that we can set an upper size limit by estimating a maximal length of 256 bytes per instruction.
> Fix JIT Machine Code Size Estimation

- src/elf.rs
- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
Reimplements the instruction tracer for the interpreter and introduces it to the JIT as well.
Now the log is not printed directly but stored in a vector and used for testing.
The tests compare the trace logs of interpreter and JIT, thus make sure that they stay in sync on an instruction level.
The display formatting of the trace log is also more efficient than before,
as it only needs to disassemble the program once instead of for each line.
This feature uncovered two bugs in the JIT which were fixed as well.
> Instruction Tracing

- src/vm.rs
Align debug behavior with release behavior when negating a value that would overflow.
> Fix negate with overflow

- src/elf.rs
- src/error.rs
- src/jit.rs
- src/vm.rs
Workaround for unresolved symbols in ELF:
Report error at runtime instead of compiletime
> JIT delay unresolved symbol to runtime

- src/jit.rs
- src/vm.rs
- Address calculation was inconsistent on overflow (using saturating_add in interpreter and wrapping_add in JIT)
- Overflowing shifts and division by zero immediate value caused interpreter to crash
- MOV32_REG actually moved 64 bits in JIT
- Division in JIT checked second register to be non zero even if an immediate value is used
- Multiplication in JIT used immediate value even if it was only between registers
- Jump targets were not validated and crashed by array bounds check in JIT
- Register bounds check, cut-in-half LD_IND_DW instructions caused JIT to crash
- LE and BE instructions immediate value was not validated in JIT
- JIT was missing bumper for the ExecutionOverrun exception
- Shifts in JIT did not handle the dst being r3 (rcx) correctly
- Shifts in JIT were not masked (could …
> Fix bugs and edge cases discovered by fuzzy testing

- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
Adds the actual fuzzy testing code which compares the execution of the interpreter and JIT instruction by instruction and reverts duplicate validation checks.
Additional fixes in JIT:
* Instruction limit was allowing one more loop iteration at last branch.
* Bugs in shift operations: There were so many that I did a complete rewrite there.
* 32 bit div and mod operations should not be sign extended.
> Test: Fuzzy + Tracer

- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
- Fixes the attack of `callx` into the middle of a `lddw` instruction (with consistent error reporting in the interpreter and JIT).
- Hardens `pc_locs` by marking it as read only.
- Refactors JIT and adds support for:
- Translating a host pc back to a bpf pc at runtime
- Resolving `special_targets` in the `pc_locs` table
- Fixes inconsistencies in the reporting of `EbpfError::CallOutsideTextSegment` with a miss-aligned target pc.
> Fix callx + lddw attack

- src/jit.rs
- tests/ubpf_execution.rs
Fixes:
- `mul r0, 0x0` producing code for `mul r0, r0` (32 bit and 64 bit) in JIT.
- Missing masking of `le16` and `le32` instructions in JIT.
> Fix JIT Inconsistencies: Multiply by constant 0 and le16 / le32 masking

- src/memory_region.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_verifier.rs
... by using the eytzinger order instead of performing a binary search on the `regions` in ascending order.
Additionally, the keys are copied into a dense vector without any gaps or stride, for better utilization of the cache.
Overall, the performance benchmarks indicate a ~ 30% speed up in address translation.
test bench_gapped_randomized_access_with_1024_entries  ... bench:          18 ns/iter (+/- 7)
test bench_mapping_with_1024_entries                   ... bench:          18 ns/iter (+/- 3)
test bench_randomized_access_with_0001_entry           ... bench:          20 ns/iter (+/- 4)
test bench_randomized_access_with_1024_entries         ... bench:          74 ns/iter (+/- 14)
test bench_randomized_mapping_access_with_0004_entries ... bench:          28 ns/iter (+/- 5)
test …
> Improves Address Translation Speed

- Cargo.lock
- src/asm_parser.rs
- src/assembler.rs
- src/disassembler.rs
- src/ebpf.rs
- src/error.rs
- src/insn_builder.rs
- src/jit.rs
- src/memory_region.rs
- src/vm.rs
- test_utils/Cargo.lock
- test_utils/Cargo.toml
- test_utils/src/lib.rs
Turns `unwrap()`, `panic!`, `assert!`, `assert_eq!`, `unreachable!`
which are not in tests, benchmarks or examples into
`unwrap_or()`, `debug_assert!`, `debug_assert_eq!`, `#[cfg(debug_assertions)]`.
Also adds error propagation to the JIT compiler.
> Fix Potential Crash Sites

- cli/src/main.rs
- src/disassembler.rs
- src/elf.rs
- src/error.rs
- src/jit.rs
- src/verifier.rs
- src/vm.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
- When placing the entrypoint to the middle of a `lddw` instruction
- Showing traces with jumps to the middle of a `lddw` instruction
- Jumps close to the max length of a program, which contains at least one `lddw` instruction
> Fix LDDW Related Bugs

- src/disassembler.rs
- src/vm.rs
- tests/disassembler.rs
* Removes the instruction index output from the tracer
* Moves the instruction pointer / PC from the last register in front of the instruction disassembly
* Adds `ebpf::ELF_INSN_DUMP_OFFSET` to PC values in tracer and disassembler
* Changes jump offset formating in the disassembler from hex to dec
> Fix PC Reporting Inconsistency

- src/jit.rs
- Replaces many of the individual handcrafted instruction assembler helper functions by one structured instruction assembler.
- Removes `OperationWidth` which was redundant and replaces its usage by `OperandSize`
- Adds support for SIB (scale, index, base, displacement) indirect operand addressing.
> JIT Machine Code Emitter

- src/jit.rs
- src/lib.rs
- src/x86.rs
- tests/ubpf_execution.rs
Fixes linear search in JIT TARGET_PC_TRANSLATE_PC.
Also, separates the x86 code emitter into its own file and makes the tests print out the trace on any failure.
> Fix JIT PC Translation

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/memory_mapping.rs
- benches/vm_execution.rs
- src/elf.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
* Adds a name field to the `SectionInfo` struct for error messages
* Throws `VirtualAddressOverlap` if adjacent `MemorRegion`s overlap in virtual address space
* Throws `OutOfBounds` if sections from `MM_PROGRAM_START` reach into `MM_STACK_START`
> Validate Overlapping Memory Regions in ELF Loader

- src/memory_region.rs
Both `&self.regions[index]` and `&self.regions[index + 1]` belong inside the `if` as they are execution path dependent.
> Fix MemoryMapping::resize_region

- src/aligned_memory.rs
- src/call_frames.rs
- src/ebpf.rs
- src/elf.rs
- src/lib.rs
The host addresses of the memory regions could be unaligned which could lead to unaligned accesses when translating a program address to a host address.  Host align the memory mapped into the program space.
> Use host aligned memory regions

- Cargo.lock
- Cargo.toml
- cli/Cargo.lock
- scripts/increment-cargo-version.sh
- test_utils/Cargo.lock
- Enforce the use of host aligned memory for regions mapping into program space
- Export aligned memory utility that can be used when passing memory into the VM that will be mapped into program space
> Fix bump to v0.2.8

- src/disassembler.rs
`to_insn_vec` can crash if the last instruction is `LD_DW_IMM`.
> Fix crash in to_insn_vec.

- src/assembler.rs
- src/disassembler.rs
- src/ebpf.rs
- src/elf.rs
- src/insn_builder.rs
- src/jit.rs
- src/vm.rs
- tests/assembler.rs
Promotes the immediate value of an instruction from `i32` to `i64`.
This way `LD_DW_IMM` can be represented by the `Insn` struct and the decoding be unified.
Also, adds the instruction pointer as an explicit field to the `Insn` struct.
> Refactor LDDW and Insn Struct Immediate Field

- src/assembler.rs
- src/elf.rs
- src/vm.rs
- tests/ubpf_execution.rs
This way it can also be set when `Exectuable::from_text_bytes()` is used.
> Generalize "entrypoint" to be a BPF Function Symbol

- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/ubpf_execution.rs
* Unifies get_symbols() and .calls in Executable.
* Preserves the name of bpf_functions so that assembler / disassembler can go full cycle.
* Less function aliasing by matching the dst PC instead of the src PC of relative calls.
* Let relative call resolution also label the functions.
> Refactoring of BPF Function Symbols in Executable

- examples/disassemble.rs
- examples/to_json.rs
- examples/uptime.rs
- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/assembler.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Unifies all inserts into `bpf_functions` in assembler and elf into `register_bpf_function()`.
Moves `register_bpf_function()` out of Executable and into `from_text_bytes()`.
Also, let `register_bpf_function()` decide the symbol hash.
Changes all test cases to use the `syscall` mnemonic.
> Fix and Refactor BPF function symbol hashing

- src/elf.rs
- src/jit.rs
- src/static_analysis.rs
Fixed collisions of `entrypoint` symbol to go unnoticed.
Also splits `hash_bpf_function` off from `register_bpf_function`.
And refactors `iter_cfg_by_function` in static_analysis.rs into a method.
> Fix Entrypoint Collision

- src/aligned_memory.rs
- src/call_frames.rs
- src/elf.rs
- src/jit.rs
AlignedMemory is doing an extraneous memset when first allocating the vector in cases where the AlignedMemory will be written to incrementally.  This memset was having a considerable performance impact when serializing large accounts.
Get rid of the extra memset and simplify the AlignedMemory handling.
> Optimized AlignedMemory

- src/elf.rs
Rust introduces .bss ELF sections that are not just called ".bss" but instead ".bss.<some stuff>".  These rw sections are not caught by the loader and thus are only discovered during program execution and reported as an access violation which is very confusing.
This PR improves the detection and reporting of read-write data
> Improve .bss reporting

- src/assembler.rs
- src/ebpf.rs
- src/error.rs
- src/verifier.rs
- src/vm.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
There are currently two bpf verifiers, one in the rbpf crate and one in the bpf_loader crate in the Solana repo.  Only the one in the bpf_loader crate is used by the cluster but having two is confusing.
This PR pulls the verifier from the bpf_loader crate and makes the necessary changes in prep for the bpf_loader crate to switch over to the updated one in the rbpf create.
> Unify BPF verifiers

- src/jit.rs
- src/vm.rs
- src/x86.rs
Homescu, Andrei, et al. ["Librando: transparent code randomization for just-in-time compilers"](https://www.ics.uci.edu/~ahomescu/ccs13librando_printed.pdf)
Proceedings of the 2013 ACM SIGSAC conference on Computer & Communications Security. 2013."
- Instruction Address Randomization: Occasional emission of additional `no-op` instructions
- Input Sanitization: Encryption of user provided values such as immediate values and offsets
- Environment Obfuscation: Encryption of registers which the compiled program uses under the hood:
- R10 - `JitProgramArgument`: The `memory_mapping` and bound `syscall_context_objects`
- RBP - Stack frame pointer
> Machinecode Diversification in JIT

- src/jit.rs
- tests/ubpf_execution.rs
> There's actually a separate issue involved, which is that if the program throws an error or panics after it was supposed to have run out of budget, then it may return a different return type. I guess this wouldn't be a problem if every error or branch into an error also first checks the compute meter (perhaps already subsumed under the conditions for returning)
_Originally posted by @jon-chuang in https://github.com/solana-labs/rbpf/issues/185#issuecomment-871833662_
> Fix JIT instruction meter limit reached before exception

- src/jit.rs
- src/memory_region.rs
The emitted x86 machinecode is currently extremely long because all address translations are inlined.
E.g. the [ec_math.so benchmark](https://github.com/solana-labs/solana/pull/17393#issuecomment-875262123) emitted 1417832 bytes and is now down to 651211 bytes. That is a reduction of 54% !
> Stop Inlining Address Translation

- src/jit.rs
- src/x86.rs
Counts CPU cycles by `lfence ; rdtsc ; lfence`
> JIT Stopwatch

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- examples/uptime.rs
- src/assembler.rs
- src/elf.rs
- src/vm.rs
- test_utils/src/lib.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Merges the `DefaultInstructionMeter` into the `TestInstructionMeter`.
> Refactoring: Default & Test Instruction Meter

- src/jit.rs
- tests/ubpf_execution.rs
The unresolved symbol exception did not check if the instruction meter reached its limit earlier.
And the syscall exception did not adjust the instruction meter after the call, leaving it in a corrupted state.
This PR also introduces a new test which covers these bugs and additionally tests nested JIT VMs via syscalls.
> Fix JIT instruction meter in syscall & unresolved symbol exceptions

- src/verifier.rs
- tests/ubpf_verifier.rs
Before this commit, the verifier didn't properly check against shift overflows in instructions that operate on 32-bit registers. Those instructions are: `lsh32_imm`, `rsh32_imm` and `arsh32_imm`.
For those instructions, the verifier used the same check for shift overflow as for instructions that operate on 64-bit registers: it called the `check_imm_shift(&insn, insn_ptr)` function, which was implemented in the following way:
```rust
/// Check that the imm is a valid shift operand
fn check_imm_shift(insn: &ebpf::Insn, insn_ptr: usize) -> Result<(), VerifierError> {
if insn.imm < 0 || insn.imm as u64 >= 64 {
return Err(VerifierError::ShiftWithOverflow(adj_insn_ptr(insn_ptr)));
}
Ok(())
}
```
Note that here, we ensure the argument is not below 0 (`insn.imm < 0`) and that it is not greater or …
> Fix verifier shift instruction overflows imm value

- src/disassembler.rs
- tests/disassembler.rs
> Make disassembler output more readable

- tests/ubpf_execution.rs
- JIT currently only works on x86_64 machines.  This change disables
usage of JIT in tests for any but the supported target architectures.
> Fix tests to pass on non-X86_64 architectures

- src/elf.rs
> Rename `ElfError::MultipleTextSections` to `ElfError::NotOneTextSection`

- src/elf.rs
The R_BPF_64_64 fixed up address is 64 bit, and two 64-bit words of a
fixed up instruction must be patched. In addition the symbols for
relocated address may be in sections other than .text, e.g. .rodata.
> Fix R_BPF_64_64 relocation handling

- Cargo.lock
- Cargo.toml
- README.md
- cli/Cargo.lock
- cli/Cargo.toml
- cli/src/main.rs
- test_utils/Cargo.lock
- test_utils/Cargo.toml
- Fix R_BPF_64_64 relocation handling (#225)
- Fixes the build of the CLI tool. (#224)
- Clearify error message MultipleTextSections => NotOneTextSection. (#223)
- Remove disabled infinite loop check (#219)
- Fix tests to pass on non-X86_64 architectures (#218)
- Fix Beta CI Tests (#216)
- Make disassembler output more readable (#215)
- Makes #212 configurable for feature gate. (#213)
- Fix verifier shift instruction overflows imm value (#212)
> Bump to v0.2.15

- .github/workflows/main.yml
Keep .travis-ci.yml for now. When gtihub actions prove to be working
as expected, remove .travis-ci.yml.
> Migrate CI from travis-ci to github actions

- src/jit.rs
- src/verifier.rs
- src/vm.rs
Makes the handling of superfluous bytes (modulo rest of program length divided by instruction size) consistent.
> Fix: Bytes at end of instruction stream

- Cargo.lock
- Cargo.toml
- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- build.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- examples/uptime.rs
- src/assembler.rs
- src/elf.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
in order to remove the workaround hacks (`vtable_send_sync_plus_one` and `REPORT_UNRESOLVED_SYMBOL_INDEX`) related to it.
> Removes the Executable dyn Trait

- src/elf.rs
- src/vm.rs
To enforce a direct mapping of file offset and virtual address space.
> Adds vm::Config::reject_section_virtual_address_file_offset_mismatch

- cli/src/main.rs
- src/assembler.rs
- src/elf.rs
- src/vm.rs
- tests/ubpf_execution.rs
There is no need for having symbol and section labels outside of debugging and the CLI tool.
> Make symbol and section labels optional

- .github/workflows/main.yml
- src/aligned_memory.rs
- src/asm_parser.rs
- src/assembler.rs
- src/call_frames.rs
- src/disassembler.rs
- src/ebpf.rs
- src/elf.rs
- src/insn_builder.rs
- src/jit.rs
- src/memory_region.rs
- src/static_analysis.rs
- src/syscalls.rs
- src/verifier.rs
- src/vm.rs
- src/x86.rs
- tests/assembler.rs
- tests/ubpf_execution.rs
But explicitly allow it in each source file so that we can eliminate unchecked integer arithmetic step by step.
> CI: Deny clippy::integer_arithmetic

- src/jit.rs
See struct definition: https://github.com/solana-labs/rbpf/blob/fca7f9049f46013aa53104eb966e5bea11c4f6dc/src/memory_region.rs#L19
> JIT emits an u8 cmp, but should be u64

- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/uptime.rs
- src/assembler.rs
- src/elf.rs
- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
#231 removed the fat-ptr and its instance pointer which had a stable location.
So this PR prevents the pointer of the `Executable` struct changing after loading and compilation by always heap allocating it.
> Wrapes Executable in a Pin Box

- src/jit.rs
When `vm::Config::encrypt_environment_registers` is enabled:
- `environment_stack_key` can overflow when adding `slot: EnvironmentStackSlot` [here](https://github.com/solana-labs/rbpf/blob/da55a12ae779ca948c635249b5417e6a094a6050/src/jit.rs#L357)
- `program_argument_key` can overflow when adding `(SYSCALL_CONTEXT_OBJECTS_OFFSET + syscall.context_object_slot) as i32 * 8` [here](https://github.com/solana-labs/rbpf/blob/da55a12ae779ca948c635249b5417e6a094a6050/src/jit.rs#L1268), and can overflow by negation [here](https://github.com/solana-labs/rbpf/blob/da55a12ae779ca948c635249b5417e6a094a6050/src/jit.rs#L1565)
> Fix: encrypt_environment_registers

- src/jit.rs
- src/x86.rs
Improves the compilation performance and size of the emitted machine code in `emit_bpf_call()` significantly by un-inlining / factoring out the common code of all BPF calls.
> Performance: JIT emit_bpf_call()

- src/assembler.rs
- src/elf.rs
- src/insn_builder.rs
- src/jit.rs
- src/static_analysis.rs
Don't call `munpam` if the size estimate was correct.
> Fix: Don't munmap nothing

- src/jit.rs
- src/x86.rs
Similar to #252 but for `syscall`, instead of `call imm` and `call reg`.
- Makes the `dst` parameter of `emit_rust_call()` more similar to `emit_bpf_call()`.
- Removes support for user_provided values in `emit_rust_call()` as that is never used.
- Change `Argument::emit_pass()` to work without using `R11` (for arguments on the stack).
- Separate the PC specific code in syscall and factors out the instruction meter, rust call and result retrieval code.
- Optimize instruction meter around syscall.
- Reduce `code_length_estimate` from 256 bytes per instruction to 110.
> Performance: JIT syscall

- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
Adds a config flag to disable the reporting of unresolved symbols at runtime.
> Feature: disable_unresolved_symbols_at_runtime

- src/elf.rs
- src/jit.rs
- src/verifier.rs
- src/vm.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Part of the SBFv2 cleanup effort https://github.com/solana-labs/solana/issues/20323
> Add option to disable ldabs* and ldind* instructions

- src/assembler.rs
- src/disassembler.rs
- tests/assembler.rs
- tests/ubpf_execution.rs
The callx instruction takes a register as an operand. The current assembly syntax makes the operand appear as an immediate however. This patch updates the assembly syntax for callx to be in line with other instructions with register operands.
> Format callx operand as register

- cli/Cargo.lock
- cli/src/main.rs
Only call `jit_compile()` if `execute_program_jit()` is used later.
Similarly, only run the analysis pass when needed.
Fixes: #279
> CLI tool independent `jit_compile()`

- src/verifier.rs
- src/vm.rs
`r10` is the stack pointer and generally points in the stack memory region.
`callx` can only jump to addresses in the program memory region.
The two memory regions don't overlap so there is no point in using `callx r10`.
> Reject `callx r10`

- src/elf.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
Syscall registration and binding are currently disjoint operations that require the callers to do both for each syscall explicitly.
This can lead to mismatch or missing registration/binds and complicates the code.  Another side effect is that it is difficult/impossible given the current API for callers to filter syscalls at the registration stage but allow them at the binding stage.  One example is the effort to deprecate/disallow syscalls by preventing new deployments of programs that rely on a disallowed syscall while continuing to support existing programs that already rely on them.
Now, all syscalls are registered once, and later the bind operation uses a common context to bind all the previously registered syscalls.  Thus, no longer requiring an explicit bind for each syscall and …
> Simplify syscall register and bind

- benches/jit_compile.rs
- benches/memory_mapping.rs
- benches/vm_execution.rs
- cli/src/main.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/call_frames.rs
- src/elf.rs
- src/helpers.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
This will allow ABIv2 in the program runtime to map individual accounts into the programs virtual address space.
> Pass custom `MemoryRegion`s to VM constructor

- cli/src/main.rs
- src/elf.rs
- src/jit.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
The RBPF side (#293) of the syscall registry changes turned out to be ok.
So this reverts #305 and brings the changes back in.
> Bring back #293

- cli/src/main.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
See discussion at https://github.com/solana-labs/rbpf/pull/293#discussion_r858556686.
> Removes the optional `hash` parameter from `bind_syscall_context_objects()`.

- cli/src/main.rs
- src/interpreter.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
- tests/ubpf_execution.rs
For a resize syscall it is required to not only be able to change the size of a `MemoryRegion`, but also its host address as that might be affected by a reallocation. This PR also exposes all existing `MemoryRegion` as readable.
Furthermore, the syscalls for CPI and resizing need mutable access to the `MemoryMapping`.
> Feature: Makes `MemoryRegion` replaceable

- src/jit.rs
- src/x86.rs
- tests/ubpf_execution.rs
`sdiv` is the only instruction which uses a `TARGET_PC_LOCAL_ANCHOR`.
In order to have all anchors registered upfront instead of patching / relocating them at the end, this local anchor must be removed.
> Refactor: Remove sdiv anchor in JIT

- fuzz/fuzz_targets/common.rs
- src/jit.rs
- src/vm.rs
- src/x86.rs
Inlines `emit_random_noop()` and avoids float arithmetic for a total speedup of compilation by about 10%.
> Speedup `X86Instruction::emit()`

- src/jit.rs
Resolve anchors and backward jumps immediately instead of relocating them.
For this purpose the subroutines were sorted, so that all anchors are set before they are called.
> Refactor: Anchor relocations in JIT

- src/jit.rs
- src/x86.rs
- Adds macro `exclude_operand_sizes`.
- Removes `PartialEq` and `Eq` in x86.rs
- Turns `X86Instruction::default()` into a `const`.
- Turns all `X86Instruction` constructors `const fn`.
> Refactor: Removes derived traits from the code emitter 

- src/jit.rs
Turns the type of `pc_section`, `anchors` and `Jump::location` from `u64` into `*const u8` and offsets them by `text_section.as_ptr()`.
> Refactor: Offset the IP/PC section

- fuzz/fuzz_targets/common.rs
- src/jit.rs
- src/vm.rs
Changes the machinecode diversification no-op insertion approach from [PDM](https://en.wikipedia.org/wiki/Pulse-density_modulation) to [PWM](https://en.wikipedia.org/wiki/Pulse-width_modulation).
The mean number of no-ops inserted stays the same.
However, as a side affect, the standard deviation (of the number of no-ops inserted) is cut in half.
> Optimize random no-op insertion

- src/jit.rs
Now that general jump targets and anchors are separate, the anchor indices can be based at `0`.
> Cleanup: Shifts down anchor indices

- src/jit.rs
- src/x86.rs
Moves the text section overflow check in the main loop.
> Refactor: Remove `Result` from all emit functions

- examples/disassemble.rs
- examples/to_json.rs
- src/assembler.rs
- src/elf.rs
- src/vm.rs
- tests/assembler.rs
- tests/ubpf_execution.rs
Use the verifier everywhere except for:
- benchmarks
- JIT `test_code_length_estimate()`
- assembler / disassembler tests
> Refactor: Use verifier in tests

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/assembler.rs
- src/elf.rs
- src/jit.rs
- src/verifier.rs
- src/vm.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Also, reorders `verify()` to happen last in `Executable::from_text_bytes()`.
`Executable::from_text_bytes()` is only used for tests and not in production (in the monorepo as well).
> Refactor: Turns verifier into a trait

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/Cargo.lock
- fuzz/Cargo.toml
- fuzz/fuzz_targets/common.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/assembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/verifier.rs
- src/vm.rs
- test_utils/src/lib.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
The code path to creating a vm allows for the executable to be optional.  The executable verification is an integral step in creating a VM and should never be optional.  This change removes the optional mechanics and requires the caller to provide a verification function in order to create a virtual machine.  Doing so will reduce the chance that a mistake is made where the executable is not verified.
The BPF loader currently does verify the ELF but the rBPF apis don't encourage good behavior or good protection to leaving out the verifier.
> Verifier is not optional

- cli/src/main.rs
- src/assembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/syscalls.rs
- src/vm.rs
- src/x86.rs
Per audit recomendations use native types rather than `std::`
> use native types

- src/aligned_memory.rs
- src/call_frames.rs
- src/elf.rs
This switches AlignedMemory to using const generics and fixes the Clone implementation.
> AlignedMemory tweaks

- examples/disassemble.rs
> Fixes the missing entrypoint in the "disassemble" example.

- src/aligned_memory.rs
- src/call_frames.rs
Use `calloc()` instead of using `malloc()` + `memset()`. The former gets zeroed memory straight from the OS, avoids writing the memory twice (once to clear old content, once to zero it) and avoids actually paging in the whole new allocation due to `memset`. See https://github.com/rust-lang/rust/issues/54628.
In practical terms, this halves memset usage while executing transactions, eliminating a frequente largeish memset in `CallFrames::new`.
Before:
After:
You can see that `memset_avx2_erms` is cut in half, and `CallFrames::new()` no longer shows up in profiles. (As for the other memsets, we'll probably be able to remove them when we implement unaligned memory mapping)
> aligned_memory: use calloc to get zeroed memory

- src/aligned_memory.rs
- src/call_frames.rs
- src/elf.rs
Follow up to #360 and designed in collaboration with @alessandrod.
- Renames `resize()` => `fill_write()`
- Optimizes away memset 0
- Adds the flag `zero_up_to_max_len` to keep track of optimization potential
- Renames `new` => `with_capacity`
- Renames `new_with_data` => `from_slice`
- Renames `new_with_size` => `zero_filled`
- Adds `with_capacity_zeroed`
> Refactor: `AlignedMemory::resize()`

- src/error.rs
- tests/ubpf_execution.rs
This PR is on behalf of Trail of Bits.
@VTCAKAVSMoACE let me know of some warnings when running my aarch64 PR (#358) under MSAN. I investigated these, and it turns out that `emit_set_exception_kind` has been writing some uninitialized bytes to the JIT region, even in the current X86 JIT.
Enum layouts are generally not well-defined, and currently the compiler is choosing to make the discriminant on `EbpfError` a u8, leaving bytes 1-7 as uninitialized stack memory:
```
100109fe1  48c785d8feffff00…  mov     qword [rbp-0x128 {var_130}], 0x0
100109fec  48c785d0feffff00…  mov     qword [rbp-0x130 {var_138}], 0x0
100109ff7  c685c8feffff0b     mov     byte [rbp-0x138 {var_140}], 0xb
100109ffe  488db5c8feffff     lea     rsi, [rbp-0x138 {var_140}]
10010a005  4889df             mov     rdi, rbx …
```
> Make EbpfError enum discriminant size explicit

- src/error.rs
- src/interpreter.rs
- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
Use a concrete type (ProgramEnvironment) instead opaquely storing everything in a vector.
> Refactor the way memory mapping, syscalls and instruction tracer are passed to programs

- Cargo.toml
- src/elf.rs
- src/lib.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
**Problem**
rbpf cannot run on wasm32 because of the `libc` dependency.
**Solution**
Make `libc` and the JIT compiler optional via a new `jit` crate feature.
> Allow interpreter-only builds

- Cargo.lock
- src/elf.rs
As that breaks the Sync trait.
Also, updates `Cargo.lock` for the added `gdbstub`.
> Fix #355: Do not use `PhantomData` if the JIT feature is active

- src/assembler.rs
- src/elf.rs
- src/jit.rs
- src/vm.rs
Solves:
> // TODO: Turn back to `executable: &mut self` once Self::report_unresolved_symbol() is gone
> Cleanup - Turn `Pin<Box<Executable<E, I>>>` back to `Executable<E, I>`

- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
Stable:
`struct { is_err: u64, err_kind: u64, payload: [u64] }`
Nightly:
`struct { err_kind: u64, payload: [u64] }` and `Ok()` is represented as `max_err_kind + 1`
> Fix: Result type encoding in JIT

- src/interpreter.rs
`CALL_IMM` handling in interpreter looks up syscall as well as bpf_function tables (when `static_syscalls` feature is not active). This could be optimized by not looking up bpf_function table if the syscall was already resolved.
This PR updates the condition when the bpf_function table is looked up.
> Lookup BPF function only if its not a syscall

- src/aligned_memory.rs
- src/elf.rs
Backport, changes taken from [#28079](https://github.com/solana-labs/solana/pull/28079).
> Refactor `AlignedMemory`

- examples/disassemble.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/assembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/assembler.rs
- tests/ubpf_execution.rs
- Stores PC addresses rather than symbol name hashes in `bpf_functions` if `config.static_syscalls` is active.
- Explicitly stores `entry_pc` in Executable.
- Defaults `entry_pc` to `0` for `Executable::new_from_text_bytes()`.
- Thus, `Executable::get_entrypoint_instruction_offset()` can not fail,
- `Executable::load_with_parser()` does not need to search for the "entrypoint" symbol by name,
- `register_bpf_function()` of "entrypoint" at PC `0` becomes unnecessary.
> Refactor - Stop hashing when static syscalls is active

- src/interpreter.rs
- src/jit.rs
- tests/ubpf_execution.rs
Depends on `Config::static_syscalls`, because it needs function symbols to be registered by their PC not their hash.
In the interpreter, simply throw `EbpfError::UnsupportedInstruction` in `callx` if the `lookup_bpf_function` of the `target_pc` fails. In the JIT, mark all instructions which are not a function symbol as `ANCHOR_CALLX_UNSUPPORTED_INSTRUCTION` in `jit.result.pc_section`.
Unfortunately, that also means that the host to guest PC translation (`ANCHOR_TRANSLATE_PC`) used by `ANCHOR_MEMORY_ACCESS_VIOLATION` won't work anymore and needs to be replaced by an explicit push of the guest / vm PC (resulting in more instructions emitted per memory access, thus longer executables produced by the JIT).
> Refactor - Restrict `callx` to registered functions

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/assembler.rs
- src/debugger.rs
- src/disassembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/static_analysis.rs
- src/syscalls.rs
- src/vm.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
Renames `syscall_context_object` to `context_object` and merges `InstructionMeter` into it.
This simplifies a few things as both are always required in the VM, and in the program runtime they are both contained in the same struct, so one pointer to them suffices.
> Refactor - ContextObject

- benches/elf_loader.rs
- src/assembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
The syscall functions were casted to `u64` and back to a (potentially different) function pointer, which allowed mismatches in the types of `context_object`.
> Refactor - Use `ContextObject` type in syscalls

- benches/elf_loader.rs
- cli/src/main.rs
- examples/to_json.rs
- src/disassembler.rs
- src/elf.rs
- src/error.rs
- src/interpreter.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
`Analysis` is now free of generic parameters and can be reused to write multiple trace logs of the same `Executable` with `Analysis::disassemble_trace_log()` independent of `TestContextObject`.
> Refactor - Move function names in `BuiltInPrograms`

- benches/memory_mapping.rs
- src/interpreter.rs
- src/jit.rs
- src/memory_region.rs
The new methods allow loading and storing values across memory region boundaries.
Say you have `[region1 vm_addr:0 len:2][region2 vm_addr:2 len:42]`, the methods allow doing loads and stores starting at `vm_addr=0` of `length > 2`, whereas calling `map()` with `len > 2` fails.
This changes the JIT and the interpreter to use the new methods for load and stores larger than one byte. `region()` is used  by the monorepo to implement memory syscalls across regions.
> Add load(), store() and region() methods to MemoryMapping

- .github/workflows/main.yml
- src/elf.rs
This fixes a failing nightly only clippy lint, and changes CI so that:
- we only run rustfmt and clippy with nightly
- we actually build and test crates on nightly (we used to build only on stable and beta before)
> Fix lints, fix ci a bit

- cli/src/main.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/debugger.rs
- src/error.rs
- src/interpreter.rs
- src/jit.rs
- src/memory_region.rs
- src/vm.rs
- test_utils/src/lib.rs
- tests/ubpf_execution.rs
In the monorepo we wrap `InstructionError` in `SyscallError` and that in turn in an `UserError`. Through the stack of VM nesting these get unpacked and repacked multiple times. All of this can be avoided by using `Box<dyn std::error::Error>` instead.
Also, this change is a preparation to unify Errors, (Program)Results and the function signatures of syscalls and built-in programs.
> Refactor - remove `EbpfError::UserError`, use `Box<dyn std::error::Error>` instead

- benches/elf_loader.rs
- src/disassembler.rs
- src/elf.rs
- src/jit.rs
- src/static_analysis.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- Renames `register_function_by_name()` => `register_function()`.
- Makes `register_function()` take `&[u8]` instead of `&str`.
> Refactor - `BuiltInProgram::register_function()`

- src/elf.rs
- src/jit.rs
- src/memory_region.rs
- src/vm.rs
The Config::enable_address_translation flag can then be disabled in the program-runtime-v2.
> Feature - Adds `MemoryMapping::Identity`

- src/elf.rs
Minor find while porting the ELF loader:
The second branch of the if expression in the writable section check is dead code.
We already check for `name.starts_with(".bss") || ?` so `name == ".bss"` is unreachable.
https://github.com/solana-labs/rbpf/blob/e9c2d206e18a5e759b63f39353b029dec6dc4247/src/elf.rs#L690-L697
The unit test for this piece of code confirms this:
https://github.com/solana-labs/rbpf/blob/e9c2d206e18a5e759b63f39353b029dec6dc4247/src/elf.rs#L2114-L2119
Related to that, we should probably add a unit test for an ELF that has a read-only `.bss` section.
> Remove unreachable BssNotSupported error

- fuzz/fuzz_targets/common.rs
- src/elf.rs
- src/memory_region.rs
- src/vm.rs
- tests/execution.rs
Issue is that SBPFv1 would no longer be able to have `optimize_rodata` and the logic for it was already present in [v0.2.31](https://github.com/solana-labs/rbpf/releases/tag/v0.2.31) which we have to stay compatible with.
> Revert - Moves Config::optimize_rodata into SBPFVersion (#477)

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/static_analysis.rs
- src/verifier.rs
- src/vm.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/execution.rs
- tests/verifier.rs
Unifies the function registries of `Executable` and `BuiltinProgram`.
> Refactor - FunctionRegistry

- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/verifier.rs
- tests/assembler.rs
Currently callx encodes its target register in the `imm` field, but it should use the `src` register field instead.
The instruction info in llvm would need to be patched here:
https://github.com/solana-labs/llvm-project/blob/7b8db05b564faffb522434b73b7082662171f94a/llvm/lib/Target/BPF/BPFInstrInfo.td#L508
> Fix - `callx` encoding

- fuzz/fuzz_targets/common.rs
- src/jit.rs
- src/vm.rs
Having `runtime_environment_key` inside `Config` is a bit of leaky abstraction as it requires the outside user to choose a key randomly and according to `PROGRAM_ENVIRONMENT_KEY_SHIFT`. It also prevents `Config::eq` from working properly as two identical configs but with different random keys would be considered different.
> Refactor - Moves `runtime_environment_key` out of `Config` into a static variable

- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/verifier.rs
- tests/execution.rs
> Refactor - Disables little-endian byte swap instructions in SBPFv2

- src/jit.rs
- src/x86.rs
This is a preparation for the upcoming changes to `mul`, `div`, `mod` instructions and their encoding. This PR is alone is incomplete and changes to the ISA / instruction encoding are planned.
> Refactor - `emit_product_quotient_remainder()` in JIT

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/assembler.rs
- src/debugger.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/static_analysis.rs
- src/verifier.rs
- src/vm.rs
- src/x86.rs
- test_utils/src/lib.rs
- tests/execution.rs
- tests/verifier.rs
In the monorepo we can now cache that a program was verified with the current `vm::Config` and skip verification when re-loading these programs. But that requires an `unsafe` transmutation to circumvent the protection here in RBPF against precisely this usage pattern. See https://github.com/solana-labs/solana/pull/32722#discussion_r1288858519.
Thus, we will just remove the type safety here as the check is effectively done at runtime now, in the loaded programs cache.
> Refactor - Remove generic parameter `Verifier` from `Executable`

- src/memory_management.rs
Allocating anonymous with mmap() should have fd set to -1 in conforming code (as 0 is a valid value for a file descriptor).
Linux is forgiving about this however other OS's (FreeBSD) less so.
This trivial change fixes BPF programs on Solana/FreeBSD which are currently broken by this.
I have copied an extract from the linux 2 mmap page for reference below.
```
MAP_ANONYMOUS
The mapping is not backed by any file; its contents are initialized to zero.  The fd argument is ignored; however, some implementations
require fd to be -1 if MAP_ANONYMOUS (or MAP_ANON) is specified, and portable applications should ensure  this.   The  offset  argument
should be zero.  The use of MAP_ANONYMOUS in conjunction with MAP_SHARED is supported on Linux only since kernel 2.4.
```
> mmap: fd should be -1 when creating anonymous mappings

- src/jit.rs
Further refactoring of the `Error` structure and its allocation is planned.
> Fix - Stops using assign for results as that drops the previously (non) existing value

- src/jit.rs
This aligns $rsp in emit_rust_call() so that if the rust code uses SIMD instructions that require alignment we don't crash
> jit: make sure RSP is 16 byte aligned when we call into rust code

- src/jit.rs
- src/vm.rs
StableResult is #[repr(C, u64)] which means that the layout is:
[u64 discriminant]
[union of all the data carried by the variants]
We were accessing the data of the Ok variant.
> jit: correctly load the StableResult discriminant in emit_result_is_err

- benches/memory_mapping.rs
- src/debugger.rs
- src/error.rs
- src/interpreter.rs
- src/jit.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
- tests/execution.rs
Stops heap allocating errors for efficiency and removes fields from runtime errors for layout stability.
The fields of these errors are mostly redundant and can be retrieved by other means anyway.
Sometimes they are completely pointless such as the `pc` field for `AccessViolation` which syscalls always set to `0`.
Also, we have much better debugging support now, so we don't need to rely on these fields for diagnosis anymore.
> Refactor - Error handling

- cli/src/main.rs
- src/jit.rs
- src/vm.rs
- test_utils/src/lib.rs
This enables us to have a single `Config` when a VM runs multiple `Executable`s.
> Refactor - Adds a reference to the loader in the VM

- src/ebpf.rs
- src/elf.rs
- src/static_analysis.rs
- src/verifier.rs
- tests/execution.rs
- tests/verifier.rs
> Cleanup - Removes `ELF_INSN_DUMP_OFFSET`

- src/interpreter.rs
- src/program.rs
- src/vm.rs
Convenience helper so that the program runtime does not have to deal with encrypting the vm pointer.
> Feature - `EbpfVm::invoke_function()`

- src/disassembler.rs
- tests/disassembler.rs
> Fix - `signed_off_str`

- src/aligned_memory.rs
- src/elf.rs
- src/jit.rs
- src/lib.rs
- src/program.rs
- src/static_analysis.rs
Credit for finding these go to @BoredPerson
> Fix - JIT second level defence

- src/jit.rs
- src/static_analysis.rs
Currently the randomized start padding can get ridiculously long if `noop_instruction_rate` is configured ridiculously high. Instead, it should just be a small constant for a maximum length.
> Fix - JIT randomized start padding length

- .github/workflows/main.yml
- src/static_analysis.rs
- tests/exercise_instructions.rs
This tests checks that all the alu instructions have the same output for jit and interpreted.
> Exercise all bpf instructions

- tests/exercise_instructions.rs
This is a follow up to #552, which did not test the `be` and `le` instructions.
> Exercise `le` instructions

- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/verifier.rs
Only relevant if `sbpf_version.static_syscalls()` is enabled.
> Fix - Verify imm not offset in CALL_IMM

- src/asm_parser.rs
- src/assembler.rs
- tests/assembler.rs
Adds an asm directive `.fill repeat, value` which will be used to generate padding in tests.
> Feature - Assembler directives

- src/interpreter.rs
- src/jit.rs
- src/program.rs
- src/verifier.rs
> Cleanup - Rename disable_lddw to enable_lddw for consistency

- src/asm_parser.rs
**Problem**
When we dump assembly from LLVM (either `llvm-objdump` or `llc`), we use a space between the register and the offset in memory operations (e.g. `[r10 - 8]`), but the assembly parser does not support it.
**Solution**
Fix the parser to accept the spaces.
> Accept blank spaces between register and offset

- src/vm.rs
- tests/execution.rs
> Tests - Increases `Config::max_call_depth` default from 20 to 64

- doc/bytecode.md
Put together from various pieces that @riptl @CantelopePeel and myself worked on 8 months ago:
https://github.com/firedancer-io/specs-old/blob/main/docs/protocol/sealevel/sbf/isa.md
https://github.com/firedancer-io/solana-improvement-documents/blob/sbpf-v2-spec/proposals/9999-sbpf-v2.md
Additionally wrote about the verifier and ISA version differences.
> Adds documentation for the VMs bytecode

- src/elf.rs
This PR removes the indirection in which the text section is retrieved from the possibly concatenated read-only sections. There is only ever one text-section and no need to concatenate it. So instead the text section can be borrowed as a sub-slice of the relocated ELF bytes directly. Also removes the `mem_size` of `text_section_info` as that was double counted and the debug name, as it was unused.
> Refactor - Separates the text section from read-only sections

- src/elf.rs
The `Section` enum for `Executable::text_section` has a `Section::Owned` variant which is never used.
Also, the virtual address could be absolute instead of relative (see https://github.com/solana-labs/rbpf/pull/553#discussion_r1670889331).
> Refactor - dissolve text section enum

- benches/vm_execution.rs
- src/assembler.rs
- src/elf.rs
- src/program.rs
- src/vm.rs
- tests/execution.rs
- tests/exercise_instructions.rs
- tests/verifier.rs
Turns the two explicit flags into a range to describe the enabled `SBPFVersion`s in the `Config` in anticipation of there being a lot more `SBPFVersion`s.
`Config::enabled_sbpf_versions` is a range and not a set because in some places we need to know the highest enabled `SBPFVersion`. Also, because features are enabled for ranges of versions themselves, it makes little sense to leave out versions in the middle of a range, so sets are needlessly verbose.
> Refactor - `Config::enabled_sbpf_versions`

- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/elf.rs
- src/verifier.rs
- tests/execution.rs
- tests/verifier.rs
Upon the activation of static syscalls, we'll no longer emit errors when a program contains an unknown syscall. This PR modifies the verifier so that we error out when this is the case.
> Check if syscall is valid during verification

- src/jit.rs
- tests/execution.rs
Thanks to @ravyu-jump, @ripatel-fd and @topointon-jump for finding this.
> Fix - JIT instruction meter in `ExecutionOverrun`

- src/jit.rs
- src/x86.rs
Reduces the machinecode emitted for:
- internal immediate calls from 60 to 47 (-22%)
- internal register calls from 67 to 36 (-46%)
> Refactor - reduce usage of `REGISTER_OTHER_SCRATCH`

- src/jit.rs
Increases the machinecode emitted for:
- store immediate from 28 to 36 (+29%)
- store register from 24 to 29 (+21%)
> Refactor - removes usage of `REGISTER_OTHER_SCRATCH`

- src/assembler.rs
- src/jit.rs
- src/program.rs
- tests/execution.rs
- tests/verifier.rs
`enum SBPF` is represented by an integer, so we can derive `Copy` for it and avoid unnecessary clones.
> Derive copy for SBPFVersion

- src/interpreter.rs
- src/jit.rs
- src/verifier.rs
- tests/execution.rs
- tests/verifier.rs
This PR depends on #609 and implements `return` in the verifier, interpreter and jitter.
> Process `return` instruction in verifier, interpreter and jitter

- src/assembler.rs
- src/disassembler.rs
- src/ebpf.rs
- src/insn_builder.rs
- src/interpreter.rs
- src/jit.rs
- src/verifier.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/verifier.rs
https://github.com/solana-foundation/solana-improvement-documents/pull/178 proposed the opcode 0x95 for syscalls in SBPFv2.
This PR modifies the assembler and the disassembler to properly deal with the new opcode and instruction format. The verifier, jitter and interpreter will be modified in follow up PRs.
> Include new `syscall` instruction in the (dis)assembler

- doc/bytecode.md
- tests/verifier.rs
-add missing verifier tests for lddw and callx
-clarify length validation and that hor64 is not available in sbpfv1
> chore: add missing verifier tests and update docs

- src/jit.rs
- tests/execution.rs
Continuation of #593 which removed the `exclusive` parameter from `emit_validate_and_profile_instruction_count()`. 
This PR removes the `exclusive` parameter from `emit_validate_instruction_count()`.
It also fixes an error priority bug in callx `ExceededMaxInstructions`.
> Fix - `emit_validate_instruction_count()` in JIT

- src/debugger.rs
- src/ebpf.rs
- src/elf.rs
- src/memory_region.rs
- src/program.rs
- tests/execution.rs
SBPFv1 allows multiple readonly sections and a single text section. All of them are concatenated and mapped into the same memory region named `MM_PROGRAM_START`.
Going forward we want to separate the bytecode (of the text section) out into its own (unmapped) region named `MM_BYTECODE_START`, which will only be executable and neither readable nor writable for memory accesses.
The `MM_PROGRAM_START` region will then become `MM_RODATA_START` because it will be readable only, and not executable anymore.
Also exports a constant `MM_REGION_SIZE` to make it easier to have multiple input sections `MM_INPUT_START + MM_REGION_SIZE * index`.
> Refactor - Virtual Address Constants

- benches/memory_mapping.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/disassembler.rs
- src/elf.rs
- src/memory_region.rs
- src/program.rs
- src/verifier.rs
- src/vm.rs
- tests/execution.rs
- tests/verifier.rs
`SBPFVersion` is represented as an integer, so using it with references is inefficient. We can remove all references and copy it everywhere.
> Do not pass `SBPFVersion` by reference

- src/disassembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/program.rs
- src/static_analysis.rs
- src/verifier.rs
- tests/execution.rs
- tests/verifier.rs
This is an alternative implementation of #614.
This PR adds the new syscall instruction to the verifier and write tests for it. It also introduces a dense function registry in the loader and distinguishes it from the sparse registry.
Execution tests for syscalls are only working for SBPFv1 and will be revamped once the instruction is properly implemented in the interpreter and jitter.
> Add new `syscall` instruction to the verifier

- examples/to_json.rs
- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/interpreter.rs
- src/jit.rs
- src/program.rs
- src/static_analysis.rs
- src/verifier.rs
- tests/assembler.rs
- tests/execution.rs
- tests/verifier.rs
In SBPFv2, the `CALL_IMM` instruction only contains relative addresses in its immediate field, so we do not need to relocate it during loading.
Also, this PR addresses the comment https://github.com/solana-labs/rbpf/pull/620/files#r1822346064, properly evaluating the address in the verifier and during execution.
> Lazily calculate target pc for `CALL_IMM`

- src/jit.rs
`ANCHOR_INTERNAL_FUNCTION_CALL_PROLOGUE` and `ANCHOR_INTERNAL_FUNCTION_CALL_REG` had been declared with two `ANCHOR` prefixes.
> Remove double `ANCHOR` prefixes

- src/interpreter.rs
- src/jit.rs
- tests/execution.rs
If we set a compute budget of N instructions and an invalid `callx` is the Nth instruction, the jitter would mistakenly throw a `ExceededMaximumInstructions` error, even though executing `callx` was still permitted (executing the very next instruction after `callx` is not). This PR patches the jitter to address this issue and fixes the interpreter to correctly count the instructions executed when `callx` errors out.
> Fix `callx` error discrepancy between interpreter and jit
