solana-labs/rbpf

- src/elf.rs
- src/lib.rs
- tests/misc.rs
Fixes: https://github.com/solana-labs/solana/issues/2177
> Respect ELF's entrypoint

- src/elf.rs
Don't panic if a shared object does not have a .rodata section
> Allow for no .rodata

- src/elf.rs
Use `?` instead of `return` where appropriate
> cleanup returns

- src/elf.rs
- src/lib.rs
Functional progams may not load due to un-referenced bad relocations
https://github.com/solana-labs/solana/issues/3108
> Ignore bad relocations (#3108)

- Cargo.toml
- src/lib.rs
A 'CALLX' uses a full stack frame
> Reg call uses frame

- .travis.yml
Disable beta and nightly automation due to this bug:
https://github.com/rust-lang/cargo/issues/7453
> Rust beta and nightly broken

- .travis.yml
Reverts: https://github.com/solana-labs/rbpf/pull/45
> Re-enable nigtly/beta CI

- src/lib.rs
`log_enabled!` checks the module-specific log code but the direct logging macros like `trace!` only check the compiled or max level.  As an example, if you call `trace!` and trace is set for any module then this call to trace will format that arguments even if `trace` is not enabled for this module.
Wrapping the `trace!` calls with `log_enabled!` avoids the wasted and expensive call to format.  To further optimize, taking the call to `log_enabled!` out of the tight loop saved another 30%.
> Re-introduce and optimize trace message

- src/ebpf.rs
- src/jit.rs
- src/verifier.rs
Will help with test cases that want to directly compare errors
> add PartialEq support to error types

- src/lib.rs
- tests/misc.rs
When running a program the caller might want to monitor the cost of the program both via direct instruction cost as well as variable costs of syscalls.  Allow the caller to pass in an object that the interpreter uses to cap instruction counts.
> Add instruction metering

- tests/misc.rs
This to prepare more tests to be unified, so that VM and JIT are tested exactly the same.
> Merge JIT and VM tests

- src/jit.rs
Also fixes wrong jump in case of no AccessViolation.
> Adds address translation to all load and store instructions in JIT.

- src/jit.rs
Fixes `mul`, `div`, `mod` and shift instructions in JIT which overwrite `RCX` without saving it.
> Fix JIT mul, div, mod and shift instructions

- examples/uptime.rs
- src/call_frames.rs
- src/jit.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_vm.rs
Allow the creator of the vm to set the maximum call depth and stack frame size
> tunable stack depth and frame size

- src/jit.rs
Moves the pointer to the optional typed return value from RDI on the stack and then moves the instruction meter from the stack into RDI.
> JIT Instruction Meter in Register

- src/error.rs
- src/memory_region.rs
Adds support to resize memory regions in memory mapping.
> Support Resizing Memory Regions

- benches/jit_compile.rs
- benches/vm_execution.rs
- examples/uptime.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
> VM constructor "mem" parameter to be mutable

- Cargo.lock
- Cargo.toml
- src/asm_parser.rs
- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/insn_builder.rs
- src/jit.rs
- src/syscalls.rs
- src/verifier.rs
- src/vm.rs
- test_utils/Cargo.lock
The dependency "combine" hat to be updated as it used a method named "try" which is now a reserved keyword.
> Rust Edition 2018

- src/elf.rs
Relocation calculations can overflow causing assertions in debug mode.  Saturate the offsets so the bounds checks fail gracefully.
> Fix arithmetic overflows

- benches/memory_mapping.rs
- src/error.rs
- src/jit.rs
- src/memory_region.rs
- src/syscalls.rs
- src/vm.rs
- tests/ubpf_execution.rs
Replaces the section list by a more descriptive section name in AccessViolation errors.
> Section Name in Access Violation

- cli/Cargo.lock
- cli/src/main.rs
- src/elf.rs
- src/vm.rs
Implements control flow graph reconstruction and profiling from tracing.
> CLI Tool: Profiling

- cli/Cargo.lock
- cli/src/main.rs
against symbols which are outside of the text section.
> Improves Robustness of CLI Tool

- src/jit.rs
Splits jumps in pc_section_jumps and text_section_jumps.
Also renames contents => text_section and pc_locs => pc_section.
> Fix JIT resolve_jumps

- cli/Cargo.lock
- cli/src/main.rs
Adds an option to verify programs before execution or disassembly in the CLI tool.
> CLI Tool Verifier Option

- src/elf.rs
- src/jit.rs
by introducing a memory management container struct.
> Fixes Memory Leak in JIT

- .travis.yml
- benches/memory_mapping.rs
- benches/vm_execution.rs
Adds benchmarks for JIT vs Interpreter performance of address translation.
> Address Translation Performance Benchmarks

- src/elf.rs
Most folks probably don't know what .bss is but they do know what read-write data is, say that instead
> Improve error description

- scripts/cargo-for-all-lock-files.sh
- scripts/increment-cargo-version.sh
- scripts/read-cargo-variable.sh
- scripts/semver.sh
Borrow release scripts form monorepo
> Add release scripts

- src/static_analysis.rs
> Fix Missing First Basic Block in Static Analysis

- src/elf.rs
> Add Missing target_pc Check in ELF Symbol Loader

- src/jit.rs
- src/vm.rs
- src/x86.rs
- tests/ubpf_execution.rs
Also adds a test (`test_err_static_jmp_lddw`) for it.
> Fixes reporting of PC in JIT when jumping into LDDW

- src/jit.rs
> Use mmap instead of memalign

- src/jit.rs
- src/vm.rs
> JIT instruction meter checkpoints

- Cargo.lock
- Cargo.toml
- cli/Cargo.lock
- test_utils/Cargo.lock
This should pacify cargo nightly clippy.
> Bump Dependency: Thiserror

- src/jit.rs
A cryptographically secure RNG is not necessary as predictability or periodic patterns are not a concern.
The purpose of the RNG is only to ensure chaotic machine code across all compilations of the same program,
so that an attack can not target any specific machine code.
This change is made to reduce the compilation performance overhead which would otherwise be caused by reseeding form hardware entropy sources.
> Fix diversification RNG performance

- cli/Cargo.lock
- cli/src/main.rs
Some maintenance of the CLI tool.
> Fixes the build of the CLI tool

- tests/ubpf_execution.rs
Adds `test_err_mem_access_out_of_bound()`.
> CI: Add more memory_region bounds check tests

- src/jit.rs
- Truncates the over allocated mmaped memory to the actual usage (rounded to the next page boundary) in `JitProgramSections::seal()`.
- Moves filling of mmaped pages to `JitProgramSections::seal()`, so that unused pages which will be thrown away are never touched.
> Performance: Truncate mmap

- src/aligned_memory.rs
- src/elf.rs
- src/jit.rs
- src/vm.rs
Add method to calc the size of a compiled executable, ugly and quick
> calc executable size

- src/jit.rs
I have noticed that a sizeable chunk of compile time goes into sanitizing constants. I've been looking at what other popular JITs do and and it seems that Chrome sanitizes only large (>= 4 bytes) constants, which seems to reduce the effectiveness of blinding tho. JavaScriptCore does what is implemented in this PR, which consists in not blinding constants that are unlikely to be usable to generate valid reusable instruction sequences. 
With spl_governance.so this brings a ~20% compilation time improvement:
before: test bench_jit_compile ... bench:   9,055,971 ns/iter (+/- 689,568)
after:  test bench_jit_compile ... bench:   7,320,170 ns/iter (+/- 527,118)
The improvement comes from emitting fewer instructions and from running the rng to generate blinding keys fewer times.
Most importantly, …
> jit: don't blind safe constants

- src/vm.rs
> Fix: LDDW instruction meter in the Interpreter

- src/static_analysis.rs
> Fix: Static analysis CFG

- src/static_analysis.rs
All CFG nodes in SCCs which do not have any incoming edges from outside their SCC are now marked as dead code.
The dead code is connected to the super root to have a common dominator parent for the entire CFG.
It is also assumed that dead code is used by `callx` and thus marked as a function.
fixes #269
> Fix static analysis: Detect dead code caused by CFG cycles

- src/static_analysis.rs
> Fix: Static analyzer CHK algorithm

- benches/memory_mapping.rs
- src/memory_region.rs
> Cleanup: MemoryMapping

- benches/elf_loader.rs
Update after register_syscall_by_name() API change in 743fb1760b46dbadd7825993875b4704fc33c024
> Fix bench build

- cli/src/main.rs
See https://github.com/solana-labs/rbpf/pull/293#issuecomment-1097963422
> Fix: bind_syscall_context_objects in the CLI tool

- src/jit.rs
This tests makes sure that the worst case of the `code_length_estimate` in the JIT holds true,
otherwise the JIT and the interpreter would diverge for programs which run over the machine code length limit.
> CI: Adds test `code_length_estimate`

- src/syscalls.rs
- removes unused BpfRand syscall which goes against the deterministic nature of the VM
- removes unused BpfSqrtI syscall
- removes `libc` dependency from `syscalls.rs`
> syscalls: remove BpfRand and BpfSqrtI

- cli/src/main.rs
- src/elf.rs
- src/jit.rs
- src/syscalls.rs
- src/vm.rs
- tests/misc.rs
- tests/ubpf_execution.rs
See https://github.com/solana-labs/solana/pull/24647
> Revert "Simplify syscall register and bind (#293)"

- src/vm.rs
- tests/ubpf_execution.rs
Small bit I forgot when I merged #274
> Set Config::dynamic_stack_frames=true by default

- src/vm.rs
> Cleanup interpreter code

- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
Looks like some changes invalidated the state of the fuzzer. This should fix them up and get them back to proper working order.
> Fix some compile issues in the fuzzers

- tests/ubpf_execution.rs
Removes two test cases of error cases from `test_err_static_jmp_lddw()` which are already caught by the verifier [here](https://github.com/solana-labs/rbpf/blob/f1237ccc8ee2c11672ab5e95a021c083faa9e07f/src/verifier.rs#L136).
> CI: Remove invalid tests

- src/jit.rs
- src/x86.rs
> JIT: Aggressively inline emitter functions

- src/jit.rs
Can't be a raw pointer otherwise `Send + Sync` can not be implemented.
> Fix: `*const u8` ptr in `JitProgramSections`

- benches/elf_loader.rs
- benches/jit_compile.rs
- benches/vm_execution.rs
- cli/src/main.rs
- examples/disassemble.rs
- examples/to_json.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- fuzz/fuzz_targets/verify_semantic_aware.rs
- src/assembler.rs
- src/elf.rs
- src/jit.rs
- src/verifier.rs
- src/vm.rs
- tests/assembler.rs
- tests/disassembler.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
This reverts commit 0ee6faf283943c272f9cfbc6268db72eda8b14f6.
These changes were not reviewed, we can add them back later after a review
> Revert "Refactor: Turns verifier into a trait (#342)"

- src/elf.rs
- src/error.rs
- src/jit.rs
- src/vm.rs
Fix nits that came from audit's findings
> audit nits

- src/aligned_memory.rs
These are like the ones in `byteorder::WriteBytesExt` but don't do bound checks. Can be used in places like during serialization where we precompute the size of the buffer then write right into it, so there's no need to do bound checks.
> AlignedMemory: add write_*_unchecked variants

- cli/src/main.rs
- src/interpreter.rs
- src/jit.rs
- src/vm.rs
Another preparation for supporting every function to be used as an entrypoint.
> Refactor - Control registers and entry of Interpreter in VM

- cli/src/main.rs
- src/asm_parser.rs
- src/assembler.rs
- src/disassembler.rs
- src/elf.rs
- src/elf_parser/mod.rs
- src/elf_parser_glue.rs
- src/static_analysis.rs
- src/syscalls.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
> Fix - Resolving function names in disassembler

- benches/jit_compile.rs
- benches/memory_mapping.rs
- benches/vm_execution.rs
- cli/src/main.rs
- fuzz/fuzz_targets/dumb.rs
- fuzz/fuzz_targets/smart.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/memory_region.rs
- src/vm.rs
- test_utils/src/lib.rs
- tests/misc.rs
- tests/ubpf_execution.rs
- tests/ubpf_verifier.rs
```
________________________
< I support MemoryRegion >
------------------------
\   ^__^
\  (oo)\_______
(__)\       )\/\
||----w |
||     ||
```
> Add CoW support to MemoryRegion

- src/memory_region.rs
This adds a bunch of missing unit tests and bumps coverage for memory_region.rs by 10%. In the process fixes a bug discovered by the new tests.
> MemoryRegion: add tests and fix unaligned mapping bug

- src/error.rs
- src/interpreter.rs
- src/jit.rs
- src/vm.rs
- tests/ubpf_execution.rs
> Cleanup - Error message wording "at BPF instruction"

- src/aarch64.rs
- src/lib.rs
This adds only the code emitter of #358, the rest is unfortunately too outdated to be merged.
> Feature - JIT code emitter stage for aarch64

- src/jit.rs
which can happen if `Config::sanitize_user_provided_values` is `false`.
> Fix - `emit_sanitized_alu()` with 64 bit immediate values

- src/disassembler.rs
- src/jit.rs
Some fixes separated out of #498 which have nothing to do with the changes to the instruction encoding.
> Minor Fixes

- Cargo.lock
- Cargo.toml
- cli/Cargo.lock
- fuzz/Cargo.lock
- src/elf.rs
- src/elf_parser/mod.rs
- src/elf_parser_glue.rs
- src/lib.rs
- src/vm.rs
- test_utils/Cargo.lock
Relevant feature has been blocked, so backing out for now and will merge in later again.
> Revert "Cleanup - old Goblin ELF parser (#525)"

- src/jit.rs
> Fix - JIT second level defence

- benches/jit_compile.rs
- benches/vm_execution.rs
- fuzz/fuzz_targets/smart_jit_diff.rs
- fuzz/fuzz_targets/smarter_jit_diff.rs
- src/lib.rs
- tests/execution.rs
- tests/exercise_instructions.rs
> Fix - cfg flags of `memory_management` module

- src/assembler.rs
> Fix - Assembler source register check

- src/interpreter.rs
- src/jit.rs
- src/program.rs
- src/x86.rs
- tests/execution.rs
See https://github.com/solana-labs/solana/issues/32924
> Feature - Explicit sign extension of results in SBPF-v2
